# Simple CI Workflow - No tokens needed!
# This workflow just runs tests to make sure everything works

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Run tests and build checks
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run setup (create demo data)
        run: npm run setup
      
      - name: Run tests
        run: npm test
      
      - name: Build application
        run: npm run build
      
      - name: Success! ✅
        run: echo "All tests passed! Your app is ready to deploy anywhere."





          