# Publish Package to npm
# This workflow publishes the package to npm when a GitHub release is created

name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build
      
      - name: Run tests
        run: npm test
      
      - name: Publish to npm
        run: npm publish --access public
